### ISSUE TITLE
Unblock subdomein advertentie.rd.nl because it is not showing ads

### ISSUE THREAD

**Issue by jkosternl** [EasyDutch-uBO/EasyDutch#124]
### Prerequisites / Vereisten

- [X] This is a **Dutch** website / Het is een **Nederlandse** website
- [X] I performed a [cursory search of the issue tracker](https://github.com/EasyDutch-uBO/EasyDutch/issues) to avoid opening a duplicate issue / Geen **duplicaten**!!
- [X] Only ads or anti-adblock / Alleen advertenties of anti-adblock
- [X] Filters were [updated](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) before reproducing an issue / Filterlijsten zijn [geüpdated](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) voordat dit probleem werd gereproduceerd
- [X] I have updated my browser to the most recent version / Ik heb mijn browser geüpdated naar de meest recente verie

### I tried to reproduce the issue when...

- [X] uBlock Origin with default lists / uBlock Origin met standaard filterlijsten
- [X] uBlock Origin is the only extension / uBlock Origin is de enige extensie

### URL(s) where the issue occurs / Website(s) waar het probleem voorkomt

https://advertentie.rd.nl

### Describe the issue

The sub domain `advertentie.rd.nl` is not showing ads, but is meant to report physical adds to the newspaper. Therefor, it should not be blocked. Currently all CSS and JS files are blocked, which shows a broken site. Easy to see. 

### Configuration / Configuratie

uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 146837
 cosmetic: 180519
 scriptlet: 40183
 html: 2094
listset (total-discarded, last-updated):
 added:
  https://www.fanboy.co.nz/enhancedstats.txt: 0-0, 24m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 97346-33293, 24m
  adguard-generic: 80446-5384, 24m
  fanboy-thirdparty_social: 68-0, 24m
  fanboy-social: 16168-17, 24m
  adguard-social: 22174-744, 24m
 default:
  user-filters: 0-0, never
  ublock-filters: 37807-123, 47m Δ
  ublock-badware: 7895-14, 47m Δ
  ublock-privacy: 740-0, 47m Δ
  ublock-unbreak: 2267-2, 47m Δ
  easylist: 81228-630, 47m Δ
  easyprivacy: 50237-871, 47m Δ
  plowe-0: 3782-1, 24m
  NLD-0: 2773-10, 24m
  urlhaus-1: 7980-0, 24m
  ublock-quick-fixes: 127-0, 47m Δ
filterset (user): [empty]
trustedset:
 added: [array of 18 redacted]
 removed:
  about-scheme
  edge-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 166 ms (selfie)
 maxAssetCacheWait: 75 ms
 cacheBackend: indexedDB

### Privacy

- [X] I agree to follow this condition / Ik ga akkoord met deze voorwaarde

**Comment by jkosternl** [comment]
I created a fork with a fix #125 but I am not totally sure if this is the right way to exclude a sub domain. I find it a bit confusing.

**Comment by jkosternl** [comment]
Hi @Nomes77, is it possible to merge this fix? Or can you adapt it, so it is merge-able? I see that you guys configured a timeout of 7 days already on issue activity and it is 'stale'.. so, I hope I didn't put this effort into this issue for nothing. 
Thanks in advance!

**Comment by jkosternl** [comment]
Can you guys process the related PR? Thanks

**Comment by jkosternl** [comment]
@Nomes77 , I know that this is not Tweakers.net, but still I'd like it to get merged, for ALL Dutch users.

**Comment by jkosternl** [comment]
Very nice how the maintainers of this repo just don't react on issues and let it just get closed automatically.... 👎🏻

**Comment by Ignotum77** [comment]
@jkosternl Life took a unforeseen turn.. 
[EasyDutch-uBlockOrigin](https://github.com/EasyDutch-uBlockOrigin/EasyDutch) is a follow up of https://github.com/EasyDutch-uBO of which I lost credentials due to circumstances of the past two years (see also https://github.com/EasyDutch-uBO/EasyDutch/issues/131#issuecomment-3831792129) https://github.com/EasyDutch-uBO/ can never be accessed by me and shall remain stale until end of time. Sadly...

However, your problem has finally been solved.

**Comment by jkosternl** [comment]
Ah, thanks for letting me know and also taking care of excluding this domain @Ignotum77. I saw devs responding and merging other issues in this repo, so I felt a bit ignored by them. Perhaps those persons were not the only maintainers, reading your message.

**Comment by Ignotum77** [comment]
There were two maintainers, me and another person. However, I didn't allow them to pull pr's...
But I understand the inconvenience you felled. I am sorry for that.
