### ISSUE TITLE
State of this repo

### ISSUE THREAD

**Issue by nicolaasjan** [EasyDutch-uBO/EasyDutch#131]
### Prerequisites / Vereisten

- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue / Geen **duplicaten**!!

### Your Question(s) / Uw vraag

Is this repo still maintained?
Contributions stopped on Jan 20 2024...

**Comment by nicolaasjan** [comment]
Bad bot. 🙁

**Comment by nicolaasjan** [comment]
As a consequence, EasyDutch has been [removed](https://github.com/gorhill/uBlock/commit/ca7d2ad61d) from uBO's default lists and replaced by AdGuard Dutch...

**Comment by Ignotum77** [comment]
> As a consequence, EasyDutch has been [removed](https://github.com/gorhill/uBlock/commit/ca7d2ad61d) from uBO's default lists and replaced by AdGuard Dutch...

This repro will be forever stale since I lost my passwords due to unforeseen circumstances of the past two years.
My new repro/org can be found here https://github.com/EasyDutch-uBlockOrigin/EasyDutch
