### ISSUE TITLE
meerdangewenst.nl anti-adblock

### ISSUE THREAD

**Issue by JohnyP36** [EasyDutch-uBO/EasyDutch#14]
### Prerequisites / Vereisten

- [X] This is a **Dutch** website / Het is een **Nederlandse** website
- [X] I performed a [cursory search of the issue tracker](https://github.com/EasyDutch-uBO/EasyDutch/issues) to avoid opening a duplicate issue / Geen **duplicaten**!!
- [X] Only ads or anti-adblock / Alleen advertenties of anti-adblock
- [X] Filters were [updated](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) before reproducing an issue / Filterlijsten zijn [geüpdated](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) voordat dit probleem werd gereproduceerd
- [X] I have updated my browser to the most recent version / Ik heb mijn browser geüpdated naar de meest recente verie

### I tried to reproduce the issue when...

- [X] uBlock Origin with default lists / uBlock Origin met standaard filterlijsten
- [X] uBlock Origin is the only extension / uBlock Origin is de enige extensie

### URL(s) where the issue occurs / Website(s) waar het probleem voorkomt

`meerdangewenst.nl`

### Describe the issue

Your commit https://github.com/EasyDutch-uBO/EasyDutch/commit/3fb26940e20f7102f9ba4a8d0ce05e27a10799ea doesn't work because the network request does not load.

I propose 
```
meerdangewenst.nl##[class*="footer-section"]:has(.sponsoren):style(visibility: hidden !important)
meerdangewenst.nl##.tg-container:has-text(/sponsors/i):style(margin-top: -175px; !important)
```

For the first rule: you have to replace this one with the cosmetic rule that's already in the list

### Configuration / Configuratie

<details>
<summary>Troubleshooting Information / Probleemoplossingsinformatie</summary>

```yaml
_No input_
```
</details>

### Privacy

- [X] I agree to follow this condition / Ik ga akkoord met deze voorwaarde

**Comment by BPower0036** [comment]
Solved in https://github.com/EasyDutch-uBO/EasyDutch/commit/b6d8e5362ad2bac750691c58f381fd12b36f8797

**Comment by JohnyP36** [comment]
I saw it. thanks
