### ISSUE TITLE
Tijd.be + confusion with EasyListDutch?

### ISSUE THREAD

**Issue by BPower0036** [EasyDutch-uBO/EasyDutch#20]
### Prerequisites / Vereisten

- [X] This is a **Dutch** website / Het is een **Nederlandse** website
- [X] I performed a [cursory search of the issue tracker](https://github.com/EasyDutch-uBO/EasyDutch/issues) to avoid opening a duplicate issue / Geen **duplicaten**!!
- [X] Only ads or anti-adblock / Alleen advertenties of anti-adblock
- [X] Filters were [updated](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) before reproducing an issue / Filterlijsten zijn [geüpdated](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) voordat dit probleem werd gereproduceerd
- [X] I have updated my browser to the most recent version / Ik heb mijn browser geüpdated naar de meest recente verie

### I tried to reproduce the issue when...

- [X] uBlock Origin with default lists / uBlock Origin met standaard filterlijsten
- [X] uBlock Origin is the only extension / uBlock Origin is de enige extensie

### URL(s) where the issue occurs / Website(s) waar het probleem voorkomt

tijd.be

### Describe the issue

See https://github.com/easylist/easylistdutch/issues/51

> Hi there,
> 
> The rule:
> 
> `tijd.be##[class^="o-hpgrid__row"]:has-text(/Gesponsorde inhoud/i)`
> 
> Is too broad; if you perform a search on tijd.be, it completely hides all search results.
> 
> Thanks in advance for looking into this!
> 
> Kind regards,
> J

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration / Configuratie

<details>
<summary>Troubleshooting Information / Probleemoplossingsinformatie</summary>

```yaml
```
</details>

### Notes

@JohannesBe since https://github.com/easylist/easylistdutch/issues/51 is closed and you ended up in the wrong repository it is already fixed in our list.

We as, EasyDutch, never intended to make a misleading name to confuse users. Sorry if it confused you. The maintainers of uBlock Origin accepted this name.

> @JohannesBe Somebody likes to play with a misleading name for his concurrent list, with the end result to confuse users, that's why you're ended up in the wrong repository.
> 
> This list never had this filter, please open the issue in the CORRECT repository.

### Privacy

- [X] I agree to follow this condition / Ik ga akkoord met deze voorwaarde

**Comment by BPower0036** [comment]
Solved in https://github.com/EasyDutch-uBO/EasyDutch/commit/6a01febf1d871c9d8661af56300fa72a972f299c and https://github.com/EasyDutch-uBO/EasyDutch/commit/7bdc1d719adc980b7bde40f4bcae4afd534e4dd5

**Comment by JohannesBe** [comment]
Hi BPower0036,

Sorry for the repository confusion.
Thanks for implementing a fix in such a short time.

Houdoe,
J
________________________________
