### ISSUE TITLE
Tweakers.net broken

### ISSUE THREAD

**Issue by nicolaasjan** [EasyDutch-uBO/EasyDutch#28]
### Prerequisites / Vereisten

- [X] This is a **Dutch** website / Het is een **Nederlandse** website
- [X] I performed a [cursory search of the issue tracker](https://github.com/EasyDutch-uBO/EasyDutch/issues) to avoid opening a duplicate issue / Geen **duplicaten**!!
- [X] Only ads or anti-adblock / Alleen advertenties of anti-adblock
- [X] Filters were [updated](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) before reproducing an issue / Filterlijsten zijn [geüpdated](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) voordat dit probleem werd gereproduceerd
- [X] I have updated my browser to the most recent version / Ik heb mijn browser geüpdated naar de meest recente verie

### I tried to reproduce the issue when...

- [X] uBlock Origin with default lists / uBlock Origin met standaard filterlijsten
- [X] uBlock Origin is the only extension / uBlock Origin is de enige extensie

### URL(s) where the issue occurs / Website(s) waar het probleem voorkomt

https://tweakers.net/nieuws/201536/lancering-sls-raket-artemis-missie-gaat-niet-door-wegens-slecht-weer.html

### Describe the issue
Firefox 106.0b3
Linux Mint 20.3

I get an almost blank page today.
Issue was not present before and also doesn't occur with EasyDutch unchecked.
Also no issue with uBO as only extension with default lists.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Schermafdruk op 2022-09-25 11-50-36](https://user-images.githubusercontent.com/14093220/192138098-01adba52-5880-4a1d-b152-4e7e4fd3c9dd.png)

</details>

### Configuration / Configuratie

<details>
<summary>Troubleshooting Information / Probleemoplossingsinformatie</summary>

```yaml
uBlock Origin: 1.44.5b3
Firefox: 106
filterset (summary): 
  network: 140234
  cosmetic: 118454
  scriptlet: 35681
  html: 793
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
    ublock-quick-fixes: null
  added: 
    https://filters.adtidy.org/extension/chromium/filters/8.txt: 1663-23, 20m
    https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/combined_original_trackers.txt: 47-0, 20m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt: 666-8, 20m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 1950-59, 20m
    https://raw.githubusercontent.com/Kees1958/W3C_annual_most_used_survey_blocklist/master/EU_US%2Bmost_used_ad_and_tracking_networks.txt: 5557-0, 20m
    https://raw.githubusercontent.com/uBlockOrigin/uAssetsCDN/main/filters/quick-fixes.txt: 241-0, 20m
    ublock-annoyances: 4846-7, 20m
    adguard-generic: 70081-5236, 16m
    adguard-spyware: 27424-1700, 20m
    adguard-social: 18648-28, 20m
    fanboy-thirdparty_social: 69-0, 20m
    RUS-0: 42230-234, 20m
    adguard-spyware-url: 763-134, 20m
    block-lan: 44-0, 20m
  default: 
    user-filters: 448-1, never
    ublock-filters: 33584-92, 16m
    ublock-badware: 4184-0, 16m
    ublock-privacy: 268-2, 20m
    ublock-abuse: 76-0, 20m
    ublock-unbreak: 1872-1, 20m
    easylist: 62647-322, 20m
    easyprivacy: 30635-13955, 20m
    NLD-0: 2459-760, 15m
    urlhaus-1: 7469-0, 20m
filterset (user): [array of 444 redacted]
trustedset: 
  added: [array of 17 redacted]
  removed: 
    about-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  added: [array of 78 redacted]
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
modifiedUserSettings: 
  advancedUserEnabled: true
  hyperlinkAuditingDisabled: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoUpdateDelayAfterLaunch: 60
  cnameMaxTTL: 60
  extensionUpdateForceReload: true
supportStats: 
  allReadyAfter: 348 ms (selfie)
  maxAssetCacheWait: 596 ms

```
</details>

### Privacy

- [X] I agree to follow this condition / Ik ga akkoord met deze voorwaarde

**Comment by BPower0036** [comment]
This is what I see when cookies are accepted:
![afbeelding](https://user-images.githubusercontent.com/80090789/192140078-1c779561-43b7-46fd-9263-a83c3933c42e.png)
And this when rejected:
![afbeelding](https://user-images.githubusercontent.com/80090789/192140082-f011f562-8a21-42d5-abc3-e456c2ef0746.png)

Maybe try adding these rules:
`tweakers.net#@##top > div > div > div:matches-css-after(content: /Advert/)`
`tweakers.net#@##contentArea > div > div:matches-css-after(content: /Advert/)`
It those doesn't work try: `tweakers.net#@#.relatedItProContent > *:has(a[href*="doubleclick.net/"])`
If this on doesn't work try:  `tweakers.net#@#div[class^="rectangle"]:has-text(/advert/i)`

**Comment by nicolaasjan** [comment]
Thanks.
```
tweakers.net#@##top > div > div > div:matches-css-after(content: /Advert/)
tweakers.net#@##contentArea > div > div:matches-css-after(content: /Advert/)
```
Only these worked. 🙂
Accepting or rejecting cookies made no difference here.

Why didn't you have the issue?

**Comment by BPower0036** [comment]
I don't know.
Maybe you were logged in and I not.

But I will remove the rules and see if that gives problems
