### ISSUE TITLE
Kijk.nl embed broken

### ISSUE THREAD

**Issue by BPower0036** [EasyDutch-uBO/EasyDutch#29]
### Prerequisites / Vereisten

- [X] This is a **Dutch** website / Het is een **Nederlandse** website
- [X] I performed a [cursory search of the issue tracker](https://github.com/EasyDutch-uBO/EasyDutch/issues) to avoid opening a duplicate issue / Geen **duplicaten**!!
- [X] Only ads or anti-adblock / Alleen advertenties of anti-adblock
- [X] Filters were [updated](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) before reproducing an issue / Filterlijsten zijn [geüpdated](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) voordat dit probleem werd gereproduceerd
- [X] I have updated my browser to the most recent version / Ik heb mijn browser geüpdated naar de meest recente verie

### I tried to reproduce the issue when...

- [X] uBlock Origin with default lists / uBlock Origin met standaard filterlijsten
- [X] uBlock Origin is the only extension / uBlock Origin is de enige extensie

### URL(s) where the issue occurs / Website(s) waar het probleem voorkomt

https://tvblik.nl/hart-van-nederland/23-oktober-2022

### Describe the issue

> Example: https://tvblik.nl/hart-van-nederland/23-oktober-2022
> 
> Results in: Je gebruikt een adblocker, zet deze uit om de leukste programma's, fragmenten en films te kunnen bekijken
> 
> Watching straight from kijk.nl seems to work without issues, haven't been able to figure out what triggers this.
> 
> ![Screenshot 2022-10-24 220419](https://user-images.githubusercontent.com/3149302/197618368-77b66236-54ee-4521-86fb-8cb9511646c3.png)
> 
> OS/version: Windows 10 x64 Browser/version: Firefox 106.0.1 Adblock Extension/version: uBO 1.44.4

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration / Configuratie

<details>
<summary>Troubleshooting Information / Probleemoplossingsinformatie</summary>

```yaml
```
</details>

### Notes

by @EchoDev
in https://github.com/easylist/easylistdutch/issues/58

### Privacy

- [X] I agree to follow this condition / Ik ga akkoord met deze voorwaarde

**Comment by BPower0036** [comment]
@EchoDev I didn't see any anti-adblock message. Maybe trying disabling `My Filters`
This is my loggor output. You can compare it to yours and see what the problem could be?

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +77 | 1x1.gif | << | embed.kijk.nl | 3,3 | image | `https://prd.jwpltx.com/v1/jwplayer6/ping.gif?h=1076369821&e=s&n=9555156494155194&abc=1&aid=UzVuSPi1EeODYiIACtqXBA&amp=0&at=1&c=2&ccp=0&cp=0&d=2&eb=0&ed=6&emi=izfvud1vxlhl&i=1&lid=188i8io1eozl&lsa=read&mt=0&pbd=1&pbr=1&pgi=1br670yj91k7&ph=0&pii=0&pl=360&plc=1&pli=16p2gc01urpe&pp=shaka&ppm=VOD&prc=1&ps=2&pss=1&pt=Aflevering%20296%2C%20Seizoen%202022&pu=https%3A%2F%2Ftvblik.nl%2F&pv=8.22.0&pyc=1&s=1&sdk=0&stc=1&stpe=0&t=Aflevering%20296%2C%20Seizoen%202022&tv=3.35.1&vb=1&vi=1&vl=90&wd=640&abm=1&bwe=9798&cae=0&cct=0&cdid=player-b294a360-5417-11ed-ad27-c7d87e278f23&dnt=1&drm=2&ff=14220&fsm=0&l=3&mk=dash&mu=https%3A%2F%2Fvod.prd1.talpatvcdn.nl%2Fe5eed8594fea42e49b65d217e51bafe1%2Fba94badf69954f2b80c8016e0ccaad3d%2Ff04bf2ba4ada4d28b0267d65f574f32e%2Findex.mpd&pcp=0&pd=3&plng=en-US&pni=0&pr=7&q=32&qcr=auto&sbr=4660&sp=0&strt=14230&tb=26&tt=0&vd=1196&vh=1080&vs=5&vw=1920&sa=1666669643159` |
| +77 | *$image,redirect-rule=1x1.gif,domain=kijk.nl | -- | embed.kijk.nl | 3,3 | image | `https://prd.jwpltx.com/v1/jwplayer6/ping.gif?h=1076369821&e=s&n=9555156494155194&abc=1&aid=UzVuSPi1EeODYiIACtqXBA&amp=0&at=1&c=2&ccp=0&cp=0&d=2&eb=0&ed=6&emi=izfvud1vxlhl&i=1&lid=188i8io1eozl&lsa=read&mt=0&pbd=1&pbr=1&pgi=1br670yj91k7&ph=0&pii=0&pl=360&plc=1&pli=16p2gc01urpe&pp=shaka&ppm=VOD&prc=1&ps=2&pss=1&pt=Aflevering%20296%2C%20Seizoen%202022&pu=https%3A%2F%2Ftvblik.nl%2F&pv=8.22.0&pyc=1&s=1&sdk=0&stc=1&stpe=0&t=Aflevering%20296%2C%20Seizoen%202022&tv=3.35.1&vb=1&vi=1&vl=90&wd=640&abm=1&bwe=9798&cae=0&cct=0&cdid=player-b294a360-5417-11ed-ad27-c7d87e278f23&dnt=1&drm=2&ff=14220&fsm=0&l=3&mk=dash&mu=https%3A%2F%2Fvod.prd1.talpatvcdn.nl%2Fe5eed8594fea42e49b65d217e51bafe1%2Fba94badf69954f2b80c8016e0ccaad3d%2Ff04bf2ba4ada4d28b0267d65f574f32e%2Findex.mpd&pcp=0&pd=3&plng=en-US&pni=0&pr=7&q=32&qcr=auto&sbr=4660&sp=0&strt=14230&tb=26&tt=0&vd=1196&vh=1080&vs=5&vw=1920&sa=1666669643159` |
| +77 | /ping.gif?$domain=~mega689.com | -- | embed.kijk.nl | 3,3 | image | `https://prd.jwpltx.com/v1/jwplayer6/ping.gif?h=1076369821&e=s&n=9555156494155194&abc=1&aid=UzVuSPi1EeODYiIACtqXBA&amp=0&at=1&c=2&ccp=0&cp=0&d=2&eb=0&ed=6&emi=izfvud1vxlhl&i=1&lid=188i8io1eozl&lsa=read&mt=0&pbd=1&pbr=1&pgi=1br670yj91k7&ph=0&pii=0&pl=360&plc=1&pli=16p2gc01urpe&pp=shaka&ppm=VOD&prc=1&ps=2&pss=1&pt=Aflevering%20296%2C%20Seizoen%202022&pu=https%3A%2F%2Ftvblik.nl%2F&pv=8.22.0&pyc=1&s=1&sdk=0&stc=1&stpe=0&t=Aflevering%20296%2C%20Seizoen%202022&tv=3.35.1&vb=1&vi=1&vl=90&wd=640&abm=1&bwe=9798&cae=0&cct=0&cdid=player-b294a360-5417-11ed-ad27-c7d87e278f23&dnt=1&drm=2&ff=14220&fsm=0&l=3&mk=dash&mu=https%3A%2F%2Fvod.prd1.talpatvcdn.nl%2Fe5eed8594fea42e49b65d217e51bafe1%2Fba94badf69954f2b80c8016e0ccaad3d%2Ff04bf2ba4ada4d28b0267d65f574f32e%2Findex.mpd&pcp=0&pd=3&plng=en-US&pni=0&pr=7&q=32&qcr=auto&sbr=4660&sp=0&strt=14230&tb=26&tt=0&vd=1196&vh=1080&vs=5&vw=1920&sa=1666669643159` |
| +63 | 1x1.gif | << | embed.kijk.nl | 3,3 | image | `https://prd.jwpltx.com/v1/clienta/ping.gif?h=-831963167&e=ae&n=2419180213538211&abc=1&aid=UzVuSPi1EeODYiIACtqXBA&amp=0&at=1&c=2&ccp=0&cp=0&d=2&eb=0&ed=6&emi=izfvud1vxlhl&i=1&lid=188i8io1eozl&lsa=read&mt=0&pbd=1&pbr=1&pgi=1br670yj91k7&ph=0&pii=0&pl=360&plc=1&pli=16p2gc01urpe&pp=shaka&ppm=VOD&prc=1&ps=2&pss=1&pt=Aflevering%20296%2C%20Seizoen%202022&pu=https%3A%2F%2Ftvblik.nl%2F&pv=8.22.0&pyc=0&s=1&sdk=0&stc=1&stpe=0&t=Aflevering%20296%2C%20Seizoen%202022&tv=3.35.1&vb=0&vi=0&vl=90&wd=640&ab=1&adi=-1&awi=1&awc=1&p=-1&pc=0&pi=0&pr=0&vu=&aec=20000&ec=900&sa=1666669628842` |
| +63 | *$image,redirect-rule=1x1.gif,domain=kijk.nl | -- | embed.kijk.nl | 3,3 | image | `https://prd.jwpltx.com/v1/clienta/ping.gif?h=-831963167&e=ae&n=2419180213538211&abc=1&aid=UzVuSPi1EeODYiIACtqXBA&amp=0&at=1&c=2&ccp=0&cp=0&d=2&eb=0&ed=6&emi=izfvud1vxlhl&i=1&lid=188i8io1eozl&lsa=read&mt=0&pbd=1&pbr=1&pgi=1br670yj91k7&ph=0&pii=0&pl=360&plc=1&pli=16p2gc01urpe&pp=shaka&ppm=VOD&prc=1&ps=2&pss=1&pt=Aflevering%20296%2C%20Seizoen%202022&pu=https%3A%2F%2Ftvblik.nl%2F&pv=8.22.0&pyc=0&s=1&sdk=0&stc=1&stpe=0&t=Aflevering%20296%2C%20Seizoen%202022&tv=3.35.1&vb=0&vi=0&vl=90&wd=640&ab=1&adi=-1&awi=1&awc=1&p=-1&pc=0&pi=0&pr=0&vu=&aec=20000&ec=900&sa=1666669628842` |
| +63 | /ping.gif?$domain=~mega689.com | -- | embed.kijk.nl | 3,3 | image | `https://prd.jwpltx.com/v1/clienta/ping.gif?h=-831963167&e=ae&n=2419180213538211&abc=1&aid=UzVuSPi1EeODYiIACtqXBA&amp=0&at=1&c=2&ccp=0&cp=0&d=2&eb=0&ed=6&emi=izfvud1vxlhl&i=1&lid=188i8io1eozl&lsa=read&mt=0&pbd=1&pbr=1&pgi=1br670yj91k7&ph=0&pii=0&pl=360&plc=1&pli=16p2gc01urpe&pp=shaka&ppm=VOD&prc=1&ps=2&pss=1&pt=Aflevering%20296%2C%20Seizoen%202022&pu=https%3A%2F%2Ftvblik.nl%2F&pv=8.22.0&pyc=0&s=1&sdk=0&stc=1&stpe=0&t=Aflevering%20296%2C%20Seizoen%202022&tv=3.35.1&vb=0&vi=0&vl=90&wd=640&ab=1&adi=-1&awi=1&awc=1&p=-1&pc=0&pi=0&pr=0&vu=&aec=20000&ec=900&sa=1666669628842` |
| +62 | /admanager_$domain=~konograma.com | -- | embed.kijk.nl | 3,1 | script | `https://static.kijk.nl/lib/Admanager_6.43.0.js` |
| +62 | @@\|\|ads-talpa.adhese.com/json/$xmlhttprequest,domain=kijk.nl | ++ | embed.kijk.nl | 3,3 | xhr | `https://ads-talpa.adhese.com/json/` |
| +62 | @@\|\|ads-talpa.adhese.com/json/$xmlhttprequest,domain=kijk.nl | ++ | embed.kijk.nl | 3,3 | xhr | `https://ads-talpa.adhese.com/json/` |
| +61 | /talpa-analytics/* | -- | embed.kijk.nl | 3,3 | script | `https://static.talpanetwork.com/prod/js/components/talpa-analytics/talpa-analytics-browser-1.2.js` |
| +61 | \|\|js-agent.newrelic.com^ | -- | embed.kijk.nl | 3,3 | script | `https://js-agent.newrelic.com/nr-spa-1209.min.js` |
| +56 | 1x1.gif | << | embed.kijk.nl | 3,3 | image | `https://prd.jwpltx.com/v1/clienta/ping.gif?h=-1401856483&e=ae&n=8022826645956941&abc=1&aid=UzVuSPi1EeODYiIACtqXBA&amp=0&at=1&c=2&ccp=0&cp=0&d=2&eb=0&ed=6&emi=a382oq5jcrju&i=1&lid=188i8io1eozl&lsa=read&mt=0&pbd=1&pbr=1&pgi=kj1ulb1tpz5j&ph=0&pii=0&pl=360&plc=1&pli=nt099bmq2czi&pp=shaka&ppm=VOD&prc=1&ps=2&pss=1&pt=Aflevering%20296%2C%20Seizoen%202022&pu=https%3A%2F%2Ftvblik.nl%2F&pv=8.22.0&pyc=0&s=1&sdk=0&stc=1&stpe=0&t=Aflevering%20296%2C%20Seizoen%202022&tv=3.35.1&vb=0&vi=0&vl=90&wd=640&ab=1&adi=-1&awi=1&awc=1&p=-1&pc=0&pi=0&pr=0&vu=&aec=20000&ec=900&sa=1666669621575` |
| +56 | *$image,redirect-rule=1x1.gif,domain=kijk.nl | -- | embed.kijk.nl | 3,3 | image | `https://prd.jwpltx.com/v1/clienta/ping.gif?h=-1401856483&e=ae&n=8022826645956941&abc=1&aid=UzVuSPi1EeODYiIACtqXBA&amp=0&at=1&c=2&ccp=0&cp=0&d=2&eb=0&ed=6&emi=a382oq5jcrju&i=1&lid=188i8io1eozl&lsa=read&mt=0&pbd=1&pbr=1&pgi=kj1ulb1tpz5j&ph=0&pii=0&pl=360&plc=1&pli=nt099bmq2czi&pp=shaka&ppm=VOD&prc=1&ps=2&pss=1&pt=Aflevering%20296%2C%20Seizoen%202022&pu=https%3A%2F%2Ftvblik.nl%2F&pv=8.22.0&pyc=0&s=1&sdk=0&stc=1&stpe=0&t=Aflevering%20296%2C%20Seizoen%202022&tv=3.35.1&vb=0&vi=0&vl=90&wd=640&ab=1&adi=-1&awi=1&awc=1&p=-1&pc=0&pi=0&pr=0&vu=&aec=20000&ec=900&sa=1666669621575` |
| +56 | /ping.gif?$domain=~mega689.com | -- | embed.kijk.nl | 3,3 | image | `https://prd.jwpltx.com/v1/clienta/ping.gif?h=-1401856483&e=ae&n=8022826645956941&abc=1&aid=UzVuSPi1EeODYiIACtqXBA&amp=0&at=1&c=2&ccp=0&cp=0&d=2&eb=0&ed=6&emi=a382oq5jcrju&i=1&lid=188i8io1eozl&lsa=read&mt=0&pbd=1&pbr=1&pgi=kj1ulb1tpz5j&ph=0&pii=0&pl=360&plc=1&pli=nt099bmq2czi&pp=shaka&ppm=VOD&prc=1&ps=2&pss=1&pt=Aflevering%20296%2C%20Seizoen%202022&pu=https%3A%2F%2Ftvblik.nl%2F&pv=8.22.0&pyc=0&s=1&sdk=0&stc=1&stpe=0&t=Aflevering%20296%2C%20Seizoen%202022&tv=3.35.1&vb=0&vi=0&vl=90&wd=640&ab=1&adi=-1&awi=1&awc=1&p=-1&pc=0&pi=0&pr=0&vu=&aec=20000&ec=900&sa=1666669621575` |
| +55 | /admanager_$domain=~konograma.com | -- | embed.kijk.nl | 3,1 | script | `https://static.kijk.nl/lib/Admanager_6.43.0.js` |
| +54 | @@\|\|ads-talpa.adhese.com/json/$xmlhttprequest,domain=kijk.nl | ++ | embed.kijk.nl | 3,3 | xhr | `https://ads-talpa.adhese.com/json/` |
| +54 | @@\|\|ads-talpa.adhese.com/json/$xmlhttprequest,domain=kijk.nl | ++ | embed.kijk.nl | 3,3 | xhr | `https://ads-talpa.adhese.com/json/` |
| +53 | /talpa-analytics/* | -- | embed.kijk.nl | 3,3 | script | `https://static.talpanetwork.com/prod/js/components/talpa-analytics/talpa-analytics-browser-1.2.js` |
| +53 | \|\|js-agent.newrelic.com^ | -- | embed.kijk.nl | 3,3 | script | `https://js-agent.newrelic.com/nr-spa-1209.min.js` |
| +51 | ##.header-banner |  | tvblik.nl |  | dom | `https://tvblik.nl/hart-van-nederland/23-oktober-2022` |
| +51 | ##.banner-fluid |  | tvblik.nl |  | dom | `https://tvblik.nl/hart-van-nederland/23-oktober-2022` |
| +51 | ##.adsbygoogle |  | tvblik.nl |  | dom | `https://tvblik.nl/hart-van-nederland/23-oktober-2022` |
| +51 | @@\|\|kijk.nl^$generichide | ++ | embed.kijk.nl | 3,1 | generichide | `https://embed.kijk.nl/?width=640&height=360&video=luwPXLOcSO7&autoplay=1&start=0` |
| +50 | \|\|improvedigital.com^ | -- | tvblik.nl | 3 | script | `https://hb.improvedigital.com/pbw/headerlift.min.js?t=home` |
| +50 | google-analytics.com/analytics.js | << | tvblik.nl | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +50 | \|\|google-analytics.com/analytics.js$script,redirect-rule=google-analytics.com/analytics.js:5 | -- | tvblik.nl | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +50 | \|\|google-analytics.com^ | -- | tvblik.nl | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +50 | \|\|improvedigital.com^ | -- | tvblik.nl | 3 | script | `https://hb.improvedigital.com/pbw/headerlift.min.js?t=home` |
| +34 | 1x1.gif | << | embed.kijk.nl | 3,3 | image | `https://prd.jwpltx.com/v1/jwplayer6/ping.gif?h=-2040421950&e=s&n=4286571576275321&abc=1&aid=UzVuSPi1EeODYiIACtqXBA&amp=0&at=1&c=2&ccp=0&cp=0&d=2&eb=0&ed=6&emi=18vttpa15ap6&i=1&lid=188i8io1eozl&lsa=read&mt=0&pbd=1&pbr=1&pgi=1r7w7lic8f8d&ph=0&pii=0&pl=360&plc=1&pli=169otzv1mtsl&pp=shaka&ppm=VOD&prc=1&ps=2&pss=1&pt=Aflevering%20296%2C%20Seizoen%202022&pu=https%3A%2F%2Ftvblik.nl%2F&pv=8.22.0&pyc=1&s=1&sdk=0&stc=1&stpe=0&t=Aflevering%20296%2C%20Seizoen%202022&tv=3.35.1&vb=1&vi=1&vl=90&wd=640&abm=1&bwe=11356&cae=0&cct=0&cdid=player-97d8eb30-5417-11ed-a07b-63de4bba6168&dnt=1&drm=2&ff=14180&fsm=0&l=3&mk=dash&mu=https%3A%2F%2Fvod.prd1.talpatvcdn.nl%2Fe5eed8594fea42e49b65d217e51bafe1%2Fba94badf69954f2b80c8016e0ccaad3d%2Ff04bf2ba4ada4d28b0267d65f574f32e%2Findex.mpd&pcp=0&pd=3&plng=en-US&pni=0&pr=7&q=32&qcr=initial%20choice&sbr=3160&sp=0&strt=14180&tb=26&tt=0&vd=1196&vh=1080&vs=5&vw=1920&sa=1666669600358` |
| +34 | *$image,redirect-rule=1x1.gif,domain=kijk.nl | -- | embed.kijk.nl | 3,3 | image | `https://prd.jwpltx.com/v1/jwplayer6/ping.gif?h=-2040421950&e=s&n=4286571576275321&abc=1&aid=UzVuSPi1EeODYiIACtqXBA&amp=0&at=1&c=2&ccp=0&cp=0&d=2&eb=0&ed=6&emi=18vttpa15ap6&i=1&lid=188i8io1eozl&lsa=read&mt=0&pbd=1&pbr=1&pgi=1r7w7lic8f8d&ph=0&pii=0&pl=360&plc=1&pli=169otzv1mtsl&pp=shaka&ppm=VOD&prc=1&ps=2&pss=1&pt=Aflevering%20296%2C%20Seizoen%202022&pu=https%3A%2F%2Ftvblik.nl%2F&pv=8.22.0&pyc=1&s=1&sdk=0&stc=1&stpe=0&t=Aflevering%20296%2C%20Seizoen%202022&tv=3.35.1&vb=1&vi=1&vl=90&wd=640&abm=1&bwe=11356&cae=0&cct=0&cdid=player-97d8eb30-5417-11ed-a07b-63de4bba6168&dnt=1&drm=2&ff=14180&fsm=0&l=3&mk=dash&mu=https%3A%2F%2Fvod.prd1.talpatvcdn.nl%2Fe5eed8594fea42e49b65d217e51bafe1%2Fba94badf69954f2b80c8016e0ccaad3d%2Ff04bf2ba4ada4d28b0267d65f574f32e%2Findex.mpd&pcp=0&pd=3&plng=en-US&pni=0&pr=7&q=32&qcr=initial%20choice&sbr=3160&sp=0&strt=14180&tb=26&tt=0&vd=1196&vh=1080&vs=5&vw=1920&sa=1666669600358` |
| +34 | /ping.gif?$domain=~mega689.com | -- | embed.kijk.nl | 3,3 | image | `https://prd.jwpltx.com/v1/jwplayer6/ping.gif?h=-2040421950&e=s&n=4286571576275321&abc=1&aid=UzVuSPi1EeODYiIACtqXBA&amp=0&at=1&c=2&ccp=0&cp=0&d=2&eb=0&ed=6&emi=18vttpa15ap6&i=1&lid=188i8io1eozl&lsa=read&mt=0&pbd=1&pbr=1&pgi=1r7w7lic8f8d&ph=0&pii=0&pl=360&plc=1&pli=169otzv1mtsl&pp=shaka&ppm=VOD&prc=1&ps=2&pss=1&pt=Aflevering%20296%2C%20Seizoen%202022&pu=https%3A%2F%2Ftvblik.nl%2F&pv=8.22.0&pyc=1&s=1&sdk=0&stc=1&stpe=0&t=Aflevering%20296%2C%20Seizoen%202022&tv=3.35.1&vb=1&vi=1&vl=90&wd=640&abm=1&bwe=11356&cae=0&cct=0&cdid=player-97d8eb30-5417-11ed-a07b-63de4bba6168&dnt=1&drm=2&ff=14180&fsm=0&l=3&mk=dash&mu=https%3A%2F%2Fvod.prd1.talpatvcdn.nl%2Fe5eed8594fea42e49b65d217e51bafe1%2Fba94badf69954f2b80c8016e0ccaad3d%2Ff04bf2ba4ada4d28b0267d65f574f32e%2Findex.mpd&pcp=0&pd=3&plng=en-US&pni=0&pr=7&q=32&qcr=initial%20choice&sbr=3160&sp=0&strt=14180&tb=26&tt=0&vd=1196&vh=1080&vs=5&vw=1920&sa=1666669600358` |
| +20 | 1x1.gif | << | embed.kijk.nl | 3,3 | image | `https://prd.jwpltx.com/v1/clienta/ping.gif?h=-1328088684&e=ae&n=9542115589595856&abc=1&aid=UzVuSPi1EeODYiIACtqXBA&amp=0&at=1&c=2&ccp=0&cp=0&d=2&eb=0&ed=6&emi=18vttpa15ap6&i=1&lid=188i8io1eozl&lsa=read&mt=0&pbd=1&pbr=1&pgi=1r7w7lic8f8d&ph=0&pii=0&pl=360&plc=1&pli=169otzv1mtsl&pp=shaka&ppm=VOD&prc=1&ps=2&pss=1&pt=Aflevering%20296%2C%20Seizoen%202022&pu=https%3A%2F%2Ftvblik.nl%2F&pv=8.22.0&pyc=0&s=1&sdk=0&stc=1&stpe=0&t=Aflevering%20296%2C%20Seizoen%202022&tv=3.35.1&vb=0&vi=0&vl=90&wd=640&ab=1&adi=-1&awi=1&awc=1&p=-1&pc=0&pi=0&pr=0&vu=&aec=20000&ec=900&sa=1666669585975` |
| +20 | *$image,redirect-rule=1x1.gif,domain=kijk.nl | -- | embed.kijk.nl | 3,3 | image | `https://prd.jwpltx.com/v1/clienta/ping.gif?h=-1328088684&e=ae&n=9542115589595856&abc=1&aid=UzVuSPi1EeODYiIACtqXBA&amp=0&at=1&c=2&ccp=0&cp=0&d=2&eb=0&ed=6&emi=18vttpa15ap6&i=1&lid=188i8io1eozl&lsa=read&mt=0&pbd=1&pbr=1&pgi=1r7w7lic8f8d&ph=0&pii=0&pl=360&plc=1&pli=169otzv1mtsl&pp=shaka&ppm=VOD&prc=1&ps=2&pss=1&pt=Aflevering%20296%2C%20Seizoen%202022&pu=https%3A%2F%2Ftvblik.nl%2F&pv=8.22.0&pyc=0&s=1&sdk=0&stc=1&stpe=0&t=Aflevering%20296%2C%20Seizoen%202022&tv=3.35.1&vb=0&vi=0&vl=90&wd=640&ab=1&adi=-1&awi=1&awc=1&p=-1&pc=0&pi=0&pr=0&vu=&aec=20000&ec=900&sa=1666669585975` |
| +20 | /ping.gif?$domain=~mega689.com | -- | embed.kijk.nl | 3,3 | image | `https://prd.jwpltx.com/v1/clienta/ping.gif?h=-1328088684&e=ae&n=9542115589595856&abc=1&aid=UzVuSPi1EeODYiIACtqXBA&amp=0&at=1&c=2&ccp=0&cp=0&d=2&eb=0&ed=6&emi=18vttpa15ap6&i=1&lid=188i8io1eozl&lsa=read&mt=0&pbd=1&pbr=1&pgi=1r7w7lic8f8d&ph=0&pii=0&pl=360&plc=1&pli=169otzv1mtsl&pp=shaka&ppm=VOD&prc=1&ps=2&pss=1&pt=Aflevering%20296%2C%20Seizoen%202022&pu=https%3A%2F%2Ftvblik.nl%2F&pv=8.22.0&pyc=0&s=1&sdk=0&stc=1&stpe=0&t=Aflevering%20296%2C%20Seizoen%202022&tv=3.35.1&vb=0&vi=0&vl=90&wd=640&ab=1&adi=-1&awi=1&awc=1&p=-1&pc=0&pi=0&pr=0&vu=&aec=20000&ec=900&sa=1666669585975` |
| +19 | /admanager_$domain=~konograma.com | -- | embed.kijk.nl | 3,1 | script | `https://static.kijk.nl/lib/Admanager_6.43.0.js` |
| +18 | @@\|\|ads-talpa.adhese.com/json/$xmlhttprequest,domain=kijk.nl | ++ | embed.kijk.nl | 3,3 | xhr | `https://ads-talpa.adhese.com/json/` |
| +18 | @@\|\|ads-talpa.adhese.com/json/$xmlhttprequest,domain=kijk.nl | ++ | embed.kijk.nl | 3,3 | xhr | `https://ads-talpa.adhese.com/json/` |
| +16 | /talpa-analytics/* | -- | embed.kijk.nl | 3,3 | script | `https://static.talpanetwork.com/prod/js/components/talpa-analytics/talpa-analytics-browser-1.2.js` |
| +16 | \|\|js-agent.newrelic.com^ | -- | embed.kijk.nl | 3,3 | script | `https://js-agent.newrelic.com/nr-spa-1209.min.js` |
| +16 | @@\|\|kijk.nl^$generichide | ++ | embed.kijk.nl | 3,1 | generichide | `https://embed.kijk.nl/?width=640&height=360&video=luwPXLOcSO7&autoplay=1&start=0` |
| +0 | \|\|improvedigital.com^ | -- | tvblik.nl | 3 | script | `https://hb.improvedigital.com/pbw/headerlift.min.js?t=home` |
| +0 | google-analytics.com/analytics.js | << | tvblik.nl | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +0 | \|\|google-analytics.com/analytics.js$script,redirect-rule=google-analytics.com/analytics.js:5 | -- | tvblik.nl | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +0 | \|\|google-analytics.com^ | -- | tvblik.nl | 3 | script | `https://www.google-analytics.com/analytics.js` |
</details>

**Comment by EchoDev** [comment]
Hi @BPower0036 

I tested around some more, disabling AdGuard Base seems to fix the issue. Something in AdGuard Base is triggering it.

I'm trying to find out which rule it is. I will let you know.

**Comment by EchoDev** [comment]
Looks like this rule is causing an issue

`kijk.nl##.pub_300x250.pub_300x250m.pub_728x90.text-ad.textAd.text_ad.text_ads.text-ads.text-ad-links:style(display: block !important;)`


Fixed it by creating a filter

`kijk.nl#@#.pub_300x250.pub_300x250m.pub_728x90.text-ad.textAd.text_ad.text_ads.text-ads.text-ad-links:style(display: block !important;)`


I haven't seen an ad yet, might be worth it to fix it in EasyDutch but not sure if you add exclusions/fixes like that to this list.

**Comment by BPower0036** [comment]
I will create your proposed filter. However Adguard should also fix it in their list, because not every one is using uBO.

**Comment by EchoDev** [comment]
I was already looking at Adguard, seems like they are on Github too, will open a ticket there!
