### ISSUE TITLE
goplay.be: ad leftover

### ISSUE THREAD

**Issue by Maiskolf** [EasyDutch-uBO/EasyDutch#39]
### Prerequisites / Vereisten

- [X] This is a **Dutch** website / Het is een **Nederlandse** website
- [X] I performed a [cursory search of the issue tracker](https://github.com/EasyDutch-uBO/EasyDutch/issues) to avoid opening a duplicate issue / Geen **duplicaten**!!
- [X] Only ads or anti-adblock / Alleen advertenties of anti-adblock
- [X] Filters were [updated](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) before reproducing an issue / Filterlijsten zijn [geüpdated](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) voordat dit probleem werd gereproduceerd
- [X] I have updated my browser to the most recent version / Ik heb mijn browser geüpdated naar de meest recente verie

### I tried to reproduce the issue when...

- [X] uBlock Origin with default lists / uBlock Origin met standaard filterlijsten
- [X] uBlock Origin is the only extension / uBlock Origin is de enige extensie

### URL(s) where the issue occurs / Website(s) waar het probleem voorkomt

https://www.goplay.be/video/de-mol/de-mol-s11/de-mol-s11-aflevering-2

### Describe the issue

Ads are blocked correctly, but the video player shows an ad layover for the time that the ads would normally play. This layover blocks player controls (e.g. you cannot skip forward or backwards) and also pauses the video when the video player is not in focus (e.g. when switching tabs). When starting the video, the layover shows for 0:45 seconds but this increases to 3:00 minutes during future ad breaks. See screenshot attached.

I was refered to report the issue here, originating from https://github.com/uBlockOrigin/uAssets/issues/17314

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/96501433/228190489-9ae73000-47ee-4f68-8e1c-3ce66b36353c.png)

</details>

### Configuration / Configuratie

<details>
<summary>Troubleshooting Information / Probleemoplossingsinformatie</summary>

```yaml
uBlock Origin: 1.48.0
Chromium: 111
filterset (summary): 
  network: 88438
  cosmetic: 41190
  scriptlet: 17383
  html: 0
listset (total-discarded, last-updated): 
  added: 
    NLD-0: 2574-14, 1h.17m
  default: 
    user-filters: 0-0, never
    easylist: 64839-48, 1h.17m
    easyprivacy: 30738-1176, 1h.17m
    plowe-0: 3751-934, 1h.17m
    ublock-abuse: 78-0, 1h.17m
    ublock-badware: 5411-114, 1h.17m
    ublock-filters: 33075-113, 1h.17m
    ublock-privacy: 295-2, 1h.17m
    ublock-unbreak: 1939-46, 1h.17m
    urlhaus-1: 6933-0, 1h.17m
filterset (user): [empty]
trustedset: 
  added: [array of 76 redacted]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2746 ms (selfie)
  maxAssetCacheWait: 78 ms

```
</details>

### Privacy

- [X] I agree to follow this condition / Ik ga akkoord met deze voorwaarde

**Comment by BPower0036** [comment]
I'm very soory for you, but I can't fix it. I have tried everything; nothing works.

**Comment by Maiskolf** [comment]
I can confirm that deleting old cookies and afterwards refusing all cookies works. Thanks!
