### ISSUE TITLE
Regels datumprikker.nl

### ISSUE THREAD

**Issue by jeroen1602** [EasyDutch-uBO/EasyDutch#45]
### Prerequisites / Vereisten

- [X] This is a **Dutch** website / Het is een **Nederlandse** website
- [X] I performed a [cursory search of the issue tracker](https://github.com/EasyDutch-uBO/EasyDutch/issues) to avoid opening a duplicate issue / Geen **duplicaten**!!
- [X] Only ads or anti-adblock / Alleen advertenties of anti-adblock
- [X] Filters were [updated](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) before reproducing an issue / Filterlijsten zijn [geüpdated](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) voordat dit probleem werd gereproduceerd
- [X] I have updated my browser to the most recent version / Ik heb mijn browser geüpdated naar de meest recente verie

### I tried to reproduce the issue when...

- [X] uBlock Origin with default lists / uBlock Origin met standaard filterlijsten
- [X] uBlock Origin is the only extension / uBlock Origin is de enige extensie

### URL(s) where the issue occurs / Website(s) waar het probleem voorkomt

https://datumprikker.nl

### Describe the issue

Datumprikker heeft een nieuwe full screen advertentie die nog niet geblokkeerd wordt.

Ik heb zelf al wat regels gemaakt, ik wist alleen niet zeker in welk betsand ik ze moest gooien vandaar een issue in plaats van een PR.

```
||datumprikker.nl/content/img/campaign/takeover/$image
datumprikker.nl##.takeover-left-gap, .takeover-right-gap, .takeover-top
datumprikker.nl##html:remove-class(takeover)
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/EasyDutch-uBO/EasyDutch/assets/1492076/0f5f2038-b084-490e-a903-e99b9c048970)

</details>

### Configuration / Configuratie

<details>
<summary>Troubleshooting Information / Probleemoplossingsinformatie</summary>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 105282
 cosmetic: 185253
 scriptlet: 25224
 html: 1116
listset (total-discarded, last-updated): 
 added: 
  adguard-annoyance: 68120-5083, 10m
  adguard-social: 20450-35, 10m
  fanboy-thirdparty_social: 68-0, 10m
  fanboy-annoyance: 90867-64779, 10m
  fanboy-cookiemonster: 47103-264, 10m
  ublock-annoyances: 4946-4, 10m
  NLD-0: 2839-47, 10m
 default: 
  user-filters: 0-0, never
  ublock-filters: 33976-69, 17h.58m
  ublock-badware: 7124-0, 18h
  ublock-privacy: 444-0, 2d.18h.42m
  ublock-abuse: 70-70, 2d.18h.41m
  ublock-unbreak: 2025-1, 17h.59m
  easylist: 66957-645, 5d.19h.18m
  easyprivacy: 32255-615, 1d.3h.25m
  urlhaus-1: 7394-1, 33m
  plowe-0: 3742-3, 2d.18h.41m
  ublock-quick-fixes: 267-0, 32m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1426 ms (selfie)
 maxAssetCacheWait: 851 ms

```
</details>

### Privacy

- [X] I agree to follow this condition / Ik ga akkoord met deze voorwaarde

**Comment by JohnyP36** [comment]
@jeroen1602 Zou jij de link van de uitnodiging kunnen delen (behalve als deze privacy gevoelig is), want momenteel kan ik de advertenties niet reproduceren. 
Ik heb even een test uitnodiging gemaakt (https://datumprikker.nl/pix7esampv9mesnh), maar ik zie daarop geen advertenties. Jij wel?
