### ISSUE TITLE
Ads on 2dehands

### ISSUE THREAD

**Issue by ThatGuyOliver** [EasyDutch-uBO/EasyDutch#47]
### Prerequisites / Vereisten

- [X] This is a **Dutch** website / Het is een **Nederlandse** website
- [X] I performed a [cursory search of the issue tracker](https://github.com/EasyDutch-uBO/EasyDutch/issues) to avoid opening a duplicate issue / Geen **duplicaten**!!
- [X] Only ads or anti-adblock / Alleen advertenties of anti-adblock
- [X] Filters were [updated](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) before reproducing an issue / Filterlijsten zijn [geüpdated](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) voordat dit probleem werd gereproduceerd
- [X] I have updated my browser to the most recent version / Ik heb mijn browser geüpdated naar de meest recente verie

### I tried to reproduce the issue when...

- [X] uBlock Origin with default lists / uBlock Origin met standaard filterlijsten
- [X] uBlock Origin is the only extension / uBlock Origin is de enige extensie

### URL(s) where the issue occurs / Website(s) waar het probleem voorkomt

https://www.2dehands.be

### Describe the issue

"This is the biggest reselling site in Belgium and there are a lot of annoying ads showing up. This is a site-wide issue."
Als je producten opzoekt krijg je eerst allemaal advertenties en als je verder bladert dan blijf je er tegen komen. Dit maakt de site bijna onbruikbaar want je vindt de particulieren niet meer terug.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration / Configuratie

<details>
<summary>Troubleshooting Information / Probleemoplossingsinformatie</summary>

```yaml
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 98989
 cosmetic: 41577
 scriptlet: 18212
 html: 1019
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 35069-100, 3m
  ublock-badware: 7687-0, 3m
  ublock-privacy: 492-0, 3m
  ublock-unbreak: 2157-0, 3m
  ublock-quick-fixes: 277-0, 3m
  easylist: 69879-704, 3m
  easyprivacy: 33276-755, 3m
  urlhaus-1: 6070-0, 3m
  plowe-0: 3718-2, 3m
  NLD-0: 2900-16, 3m
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1671 ms (selfie)
 maxAssetCacheWait: 121 ms
popupPanel:
 blocked: 9
 network:
  datadoghq-browser-agent.com: 1
  ebayclassifieds.net: 4
  google-analytics.com: 1
  googletagmanager.com: 1
  marktplaats.net: 2
 extended:
  ###adsense-container
  ###banner-top-dt
  ##.hz-Banner
  ##.hz-Page-content:style(max-width: 1300px!important;)
```
</details>

### Notes

Ik ben naar hier verwezen vanaf uBlockOrigin. Ik heb geen instellingen aangepast.

### Privacy

- [X] I agree to follow this condition / Ik ga akkoord met deze voorwaarde

**Comment by BPower0036** [comment]
https://github.com/uBlockOrigin/uAssets/issues/19355#issuecomment-1680115305
> In my opinion those "Top advertisements" are not advertisements. Everything on this reselling website are advertisements of people trying to sell their products. "Top advertisements" are advertisements of people of people who paid to be higher up in the rankings, or am I wrong @ThatGuyOliver?
