### ISSUE TITLE
Was adding the Suriname flag intentional or was it by mistake?

### ISSUE THREAD

**Issue by SnowballV** [EasyDutch-uBO/EasyDutch#92]
### Prerequisites / Vereisten

- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue / Geen **duplicaten**!!

### Your Question(s) / Uw vraag

In uBlock Origin, My filters, I notice a new, second flag icon with EasyDutch.
The new flag did not show in uBlock Origin, My filters, before today.
It is the Suriname flag.

The EasyDutch description says:
Dutch supplement for the Easylist filters to use with uBlock Origin
Only for ads or anti-adblock on Dutch sites!
Does also support Afrikaans, since it is a sort of Dutch

I see that accepting entries for Afrikaans sites was discussed last May, https://github.com/EasyDutch-uBO/EasyDutch/issues/41

The new flag and .sr Internet country code top-level domain are not for South Africa, but for Suriname.
I wonder if adding the Suriname flag was intentional or if it was by mistake.

**Comment by JohnyP36** [comment]
I'm not aware of this change. We support some Suriname domains. I will investigated this, as uBlock itself might have added it and not we.

**Comment by SnowballV** [comment]
Thanks very much for investigating.
If case you find that not EasyDutch but uBlock Origin added it, where do I report?

**Comment by JohnyP36** [comment]
> If case you find that not EasyDutch but uBlock Origin added it, where do I report?

We are reporting it to them.

**Comment by SnowballV** [comment]
Ah, OK, thanks very much!

**Comment by DandelionSprout** [comment]
The Suriname flag was in fact intended by me (as in, not a mistake), seeing as Dutch is the sole main language there, so I figured "Hmm, it'd probably make more sense to add that flag, than to add the flags of Belgium or South Africa where Dutch is not the sole main language".

That's at least what my mindset was at the time.

**Comment by DandelionSprout** [comment]
>If case you find that not EasyDutch but uBlock Origin added it, where do I report?

I suppose there's https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aopen+is%3Aissue

**Comment by JohnyP36** [comment]
@Nomes77 What are your thoughts on this? 
Should we keep the change made by DandelionSprout? 
And what about Belgium and South Africa? Belgium has 3 official languages and South Africa 11 and we are definitely not supporting all those other languages. 

Thus, should we add to our description that we support Suriname domains? 
*(But "de voertaal en officiële taal is het Nederlands, terwijl het Sranan(tongo) vooral als lingua franca gebruikt wordt, als communicatiemiddel tussen de verschillende etniciteiten")*

**Comment by DandelionSprout** [comment]
I know I covered two .sr sites last year; I'm currently working on covering a third (`sun.sr`) as a sort of apology for this whole situation.

**Comment by gorhill** [comment]
Actually I would like to understand why this is seen as an issue. If a list covers a specific country TLD, it makes sense to signal this in the user interface.

**Comment by SnowballV** [comment]
@gorhill,
I posted as a question. Adding the Suriname flag was unexpected to me. I hadn't thought the criteria were met for adding the Suriname flag. After reading everyone's comments, I understand.

**Comment by JohnyP36** [comment]
> Actually I would like to understand why this is seen as an issue. If a list covers a specific country TLD, it makes sense to signal this in the user interface.

> One of the criteria is that there should a the TLD of the country in the list. I've seen instances of .sr in EasyDutch.

It's not so much a problem, but then also `.za` should be added as there are 5 instances of South African domains are in your list. And also `.be` as there are also a lot of Belgium domains.

**Comment by DandelionSprout** [comment]
I'll make sure to @ list owners next time I'd add a flag, at least, to more quickly (and less surprisingly on their part) get to hear from them first-hand. I am a man who am able to learn from my mistakes.

**Comment by Nomes77** [comment]
@ Everyone, I as the head owner of EasyDutch agree with adding the flags of the country TLD's we support. And since we support `.nl`, `.be`, `.sr` and `.za` or every other Surinamian or South African website which is in Duth/Dutch-like language, what @gorhill has done by adding the `.sr` flag is totally fine.

**Comment by gorhill** [comment]
There could be a threshold to pass regarding the number of instances of a TLD.

**Comment by JohnyP36** [comment]
> There could be a threshold to pass regarding the number of instances of a TLD.

As `.sr` passes the threshold then `.be` surly passes the threshold.

**Comment by Nomes77** [comment]
We have in our list 3 `.sr` websites and also 3 `.za` websites and around 40 `.be` websites.

**Comment by gorhill** [comment]
For now I set a threshold of 5%, so searching for `.sr` yielded 10 lines out of 2,374, while `.be` yielded 285 -- so I remore the Suriname flag and added the Belgium one.

**Comment by Nomes77** [comment]
@gorhill One little thing. According to Wikipedia the official language of Suriname is Dutch.
> Suriname has roughly 14 local languages, but Dutch (Nederlands) is the sole official language and is the language used in education, government, business, and the media.[[14]](https://en.wikipedia.org/wiki/Suriname#cite_note-cia-16) Over 60% of the population are native speakers of Dutch[[93]](https://en.wikipedia.org/wiki/Suriname#cite_note-taalgebied-96) and around 20%–30% speak it as a second language. In 2004, Suriname became an associate member of the [Dutch Language Union](https://en.wikipedia.org/wiki/Dutch_Language_Union).[[94]](https://en.wikipedia.org/wiki/Suriname#cite_note-97)

Currently we gave 21 rules for Suriname websites (not all of them have `.sr`). Since Suriname is a small country what not many websites we are never going to pass the threshold of 5%.

So, with this information, if you want to add the flag to `assets.json` I am ok, if not I'm still ok.

For South Africa, it is a different case since it has 12 official languages.
