### ISSUE TITLE
add npo.nl, previously npostart.nl

### ISSUE THREAD

**Issue by FrisoDB** [EasyDutch-uBO/EasyDutch#98]
### Prerequisites / Vereisten

- [X] This is a **Dutch** website / Het is een **Nederlandse** website
- [X] I performed a [cursory search of the issue tracker](https://github.com/EasyDutch-uBO/EasyDutch/issues) to avoid opening a duplicate issue / Geen **duplicaten**!!
- [X] Only ads or anti-adblock / Alleen advertenties of anti-adblock
- [X] Filters were [updated](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) before reproducing an issue / Filterlijsten zijn [geüpdated](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) voordat dit probleem werd gereproduceerd
- [X] I have updated my browser to the most recent version / Ik heb mijn browser geüpdated naar de meest recente verie

### I tried to reproduce the issue when...

- [X] uBlock Origin with default lists / uBlock Origin met standaard filterlijsten
- [X] uBlock Origin is the only extension / uBlock Origin is de enige extensie

### URL(s) where the issue occurs / Website(s) waar het probleem voorkomt

https://npo.nl/start/serie/podium-klassiek/seizoen-2/podium-klassiek_10

### Describe the issue

NPO(start) has a new website and also a new way of showing ads.
When playing around with the logger and static filters, the following seems to solve it. 

! 2023-11-14 https://npo.nl
||cdn-ster-nl.akamaized.net^

I just don't know how to add this to the filterlist.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration / Configuratie

<details>
<summary>Troubleshooting Information / Probleemoplossingsinformatie</summary>

```yaml
<!-- Put the copied text here, by replacing this line / Zet hier de gekopieerde tekst neer, door deze regel te overschrijven -->
```
</details>

### Privacy

- [X] I agree to follow this condition / Ik ga akkoord met deze voorwaarde

**Comment by JohnyP36** [comment]
Recently we added `||akamaized.net^$media,domain=npo.nl,redirect=noopmp3-0.1s`. See https://github.com/EasyDutch-uBO/EasyDutch/commit/645f5d1453a5def89ae5c2e78cfe4b37ad639e1f. This should fix the issue. 
You can manually force update your filterlist in order to get this patch.

**Comment by FrisoDB** [comment]
forced update an extra time, and now it works
